### ISSUE TITLE
전화번호 인증

### ISSUE THREAD

**Issue by sangu1026** [practice-workflow/test1#2]
## 📄 설명
SOLAPI API를 활용하여 지정 핸드폰으로 인증번호를 보내고
해당 인증번호를 우리 앱에 입력했을때 인증 완료 되는 기능 구현

---

## ✅ TO-DO-LIST
- [ ] 인증 코드 만드는 service 구현
- [ ] 인증 코드를 핸드폰으로 전송하는 기능 구현
- [ ] 인증된 핸드폰 데이터베이스에 저장

---

## 고민해볼 점
- 문자 메시지를 보낼 때 1차적인 비용이 들어가는 부분이라 만약 유저가 비정상적인 요청을 했을 때 어떻게 처리 할 것 인가
- 요금 지불 방식 알아보기

---

## 🙋🏻 참고 자료
https://solapi.com/
